<?php

return [
    'groups' => [
        'brand' => [
            'label' => 'Brand',
            'description' => 'Brand identity and company details shown in customer-facing documents.',
            'visible' => true,
            'onboarding' => false,
            'fields' => [
                'company_name' => ['label' => 'Company name', 'type' => 'string', 'required' => true, 'default' => null, 'max' => 255],
                'logo_path' => ['label' => 'Logo', 'type' => 'file', 'required' => false, 'default' => null, 'image' => true, 'max' => 5120],
                'primary_color' => ['label' => 'Primary color', 'type' => 'color', 'required' => false, 'default' => '#4F46E5'],
                'accent_color' => ['label' => 'Accent color', 'type' => 'color', 'required' => false, 'default' => '#F5A623'],
                'font_family' => ['label' => 'Font family', 'type' => 'string', 'required' => false, 'default' => 'Inter', 'max' => 100],
                'company_address' => ['label' => 'Company address', 'type' => 'text', 'required' => false, 'default' => null],
                'company_phone' => ['label' => 'Company phone', 'type' => 'string', 'required' => false, 'default' => null, 'max' => 50],
                'company_email' => ['label' => 'Company email', 'type' => 'email', 'required' => false, 'default' => null, 'max' => 255],
                'company_website' => ['label' => 'Company website', 'type' => 'url', 'required' => false, 'default' => null, 'max' => 255],
                'company_tagline' => ['label' => 'Company tagline', 'type' => 'string', 'required' => false, 'default' => null, 'max' => 255],
                'tax_number' => ['label' => 'Tax number', 'type' => 'string', 'required' => false, 'default' => null, 'max' => 100],
                'white_label_mode' => ['label' => 'White-label mode', 'type' => 'boolean', 'required' => false, 'default' => false],
                'custom_domain' => ['label' => 'Custom domain', 'type' => 'string', 'required' => false, 'default' => null, 'max' => 255],
                'favicon_path' => ['label' => 'Favicon path', 'type' => 'string', 'required' => false, 'default' => null, 'max' => 512],
            ],
        ],
        'quotes_invoices' => [
            'label' => 'Quotes & Invoices',
            'description' => 'Defaults used when creating and formatting quotes and invoices.',
            'visible' => true,
            'onboarding' => true,
            'subsections' => [
                'quotes' => [
                    'label' => 'Quotes',
                    'fields' => [
                        'quote_prefix' => ['label' => 'Quote prefix', 'type' => 'string', 'required' => true, 'default' => 'QS', 'max' => 20],
                        'quote_number_sequence' => ['label' => 'Quote sequence', 'type' => 'integer', 'required' => true, 'default' => 1, 'min' => 1],
                        'quote_number_reset_yearly' => ['label' => 'Reset sequence yearly', 'type' => 'boolean', 'required' => false, 'default' => true],
                        'quote_validity_days' => ['label' => 'Quote validity days', 'type' => 'integer', 'required' => true, 'default' => 30, 'min' => 1, 'max' => 365],
                        'default_tax_label' => ['label' => 'Default tax label', 'type' => 'select', 'required' => false, 'default' => 'VAT', 'options' => ['VAT', 'GST', 'Sales Tax', 'None']],
                        'default_tax_rate' => ['label' => 'Default tax rate', 'type' => 'float', 'required' => false, 'default' => 0, 'min' => 0, 'max' => 100],
                        'tax_inclusive' => ['label' => 'Tax inclusive pricing', 'type' => 'boolean', 'required' => false, 'default' => false],
                        'show_line_item_tax' => ['label' => 'Show line item tax', 'type' => 'boolean', 'required' => false, 'default' => true],
                        'show_unit_prices' => ['label' => 'Show unit prices', 'type' => 'boolean', 'required' => false, 'default' => true],
                        'show_cost_price' => ['label' => 'Show cost price', 'type' => 'boolean', 'required' => false, 'default' => false],
                        'require_cover_message' => ['label' => 'Require cover message', 'type' => 'boolean', 'required' => false, 'default' => false],
                        'default_cover_message' => ['label' => 'Default cover message', 'type' => 'text', 'required' => false, 'default' => null],
                        'default_terms' => ['label' => 'Default terms', 'type' => 'text', 'required' => false, 'default' => null],
                        'default_payment_terms' => ['label' => 'Default payment terms', 'type' => 'string', 'required' => false, 'default' => 'Net 30', 'max' => 100],
                        'default_notes' => ['label' => 'Default notes', 'type' => 'text', 'required' => false, 'default' => null],
                        'allow_client_negotiation' => ['label' => 'Allow client negotiation', 'type' => 'boolean', 'required' => false, 'default' => false],
                        'allow_optional_items' => ['label' => 'Allow optional items', 'type' => 'boolean', 'required' => false, 'default' => true],
                        'require_deposit' => ['label' => 'Require deposit', 'type' => 'boolean', 'required' => false, 'default' => false],
                        'default_deposit_percent' => ['label' => 'Default deposit percent', 'type' => 'float', 'required' => false, 'default' => 50, 'min' => 0, 'max' => 100],
                        'show_margin_to_roles' => ['label' => 'Roles that can view margin', 'type' => 'array', 'required' => false, 'default' => ['owner', 'admin'], 'options' => ['owner', 'admin']],
                    ],
                ],
                'invoices' => [
                    'label' => 'Invoices',
                    'fields' => [
                        'invoice_prefix' => ['label' => 'Invoice prefix', 'type' => 'string', 'required' => true, 'default' => 'INV', 'max' => 20],
                        'invoice_number_sequence' => ['label' => 'Invoice sequence', 'type' => 'integer', 'required' => true, 'default' => 1, 'min' => 1],
                        'invoice_number_reset_yearly' => ['label' => 'Reset sequence yearly', 'type' => 'boolean', 'required' => false, 'default' => true],
                        'default_invoice_terms' => ['label' => 'Default invoice terms', 'type' => 'text', 'required' => false, 'default' => null],
                        'default_payment_terms' => ['label' => 'Default payment terms', 'type' => 'string', 'required' => false, 'default' => 'Net 30', 'max' => 100],
                    ],
                ],
                'credit_notes' => [
                    'label' => 'Credit Notes',
                    'fields' => [
                        'credit_note_prefix' => ['label' => 'Credit note prefix', 'type' => 'string', 'required' => true, 'default' => 'CN', 'max' => 20],
                        'credit_note_number_sequence' => ['label' => 'Credit note sequence', 'type' => 'integer', 'required' => true, 'default' => 1, 'min' => 1],
                        'credit_note_number_reset_yearly' => ['label' => 'Reset sequence yearly', 'type' => 'boolean', 'required' => false, 'default' => true],
                    ],
                ],
            ],
        ],
        'quotes' => [
            'label' => 'Quotes',
            'description' => 'Defaults used when creating and formatting quotes.',
            'visible' => false,
            'onboarding' => false,
            'fields' => [
                'quote_prefix' => ['label' => 'Quote prefix', 'type' => 'string', 'required' => true, 'default' => 'QS', 'max' => 20],
                'quote_number_sequence' => ['label' => 'Quote sequence', 'type' => 'integer', 'required' => true, 'default' => 1, 'min' => 1],
                'quote_number_reset_yearly' => ['label' => 'Reset sequence yearly', 'type' => 'boolean', 'required' => false, 'default' => true],
                'quote_validity_days' => ['label' => 'Quote validity days', 'type' => 'integer', 'required' => true, 'default' => 30, 'min' => 1, 'max' => 365],
                'require_cover_message' => ['label' => 'Require cover message', 'type' => 'boolean', 'required' => false, 'default' => false],
                'default_cover_message' => ['label' => 'Default cover message', 'type' => 'text', 'required' => false, 'default' => null],
                'default_terms' => ['label' => 'Default terms', 'type' => 'text', 'required' => false, 'default' => null],
                'default_payment_terms' => ['label' => 'Default payment terms', 'type' => 'text', 'required' => false, 'default' => null],
                'default_notes' => ['label' => 'Default notes', 'type' => 'text', 'required' => false, 'default' => null],
                'allow_client_negotiation' => ['label' => 'Allow client negotiation', 'type' => 'boolean', 'required' => false, 'default' => false],
                'allow_optional_items' => ['label' => 'Allow optional items', 'type' => 'boolean', 'required' => false, 'default' => true],
                'require_deposit' => ['label' => 'Require deposit', 'type' => 'boolean', 'required' => false, 'default' => false],
                'default_deposit_percent' => ['label' => 'Default deposit percent', 'type' => 'float', 'required' => false, 'default' => 50, 'min' => 0, 'max' => 100],
            ],
        ],
        'invoices' => [
            'label' => 'Invoices',
            'description' => 'Defaults used when creating and formatting invoices.',
            'visible' => false,
            'onboarding' => false,
            'fields' => [
                'invoice_prefix' => ['label' => 'Invoice prefix', 'type' => 'string', 'required' => true, 'default' => 'INV', 'max' => 20],
                'invoice_number_sequence' => ['label' => 'Invoice sequence', 'type' => 'integer', 'required' => true, 'default' => 1, 'min' => 1],
                'invoice_number_reset_yearly' => ['label' => 'Reset sequence yearly', 'type' => 'boolean', 'required' => false, 'default' => true],
                'default_invoice_terms' => ['label' => 'Default invoice terms', 'type' => 'text', 'required' => false, 'default' => null],
                'invoice_payment_terms' => ['label' => 'Default payment terms', 'type' => 'text', 'required' => false, 'default' => null],
            ],
        ],
        'email' => [
            'label' => 'Email',
            'description' => 'Sender, delivery provider, and template settings for quote communications.',
            'visible' => true,
            'onboarding' => false,
            'fields' => [
                'email_enabled' => ['label' => 'Enable custom email', 'type' => 'boolean', 'required' => false, 'default' => false],
                'delivery_provider_enabled' => ['label' => 'Configure delivery provider', 'type' => 'boolean', 'required' => false, 'default' => false],
                'from_name' => ['label' => 'From name', 'type' => 'string', 'required' => false, 'default' => null, 'max' => 255],
                'from_email' => ['label' => 'From email', 'type' => 'email', 'required' => false, 'default' => null, 'max' => 255],
                'reply_to_email' => ['label' => 'Reply-to email', 'type' => 'email', 'required' => false, 'default' => null, 'max' => 255],
                'email_driver' => ['label' => 'Email driver', 'type' => 'select', 'required' => false, 'default' => 'smtp', 'options' => ['smtp', 'resend', 'mailgun']],
                'smtp_host' => ['label' => 'SMTP host', 'type' => 'string', 'required' => false, 'default' => null, 'max' => 255],
                'smtp_port' => ['label' => 'SMTP port', 'type' => 'integer', 'required' => false, 'default' => 587, 'min' => 1, 'max' => 65535],
                'smtp_username' => ['label' => 'SMTP username', 'type' => 'string', 'required' => false, 'default' => null, 'max' => 255],
                'smtp_password' => ['label' => 'SMTP password', 'type' => 'string', 'required' => false, 'default' => null, 'encrypted' => true, 'max' => 255],
                'smtp_encryption' => ['label' => 'SMTP encryption', 'type' => 'select', 'required' => false, 'default' => 'tls', 'options' => ['tls', 'ssl', 'none']],
                'resend_api_key' => ['label' => 'Resend API key', 'type' => 'string', 'required' => false, 'default' => null, 'encrypted' => true, 'max' => 255],
                'mailgun_api_key' => ['label' => 'Mailgun API key', 'type' => 'string', 'required' => false, 'default' => null, 'encrypted' => true, 'max' => 255],
                'mailgun_domain' => ['label' => 'Mailgun domain', 'type' => 'string', 'required' => false, 'default' => null, 'max' => 255],
                'quote_email_subject' => ['label' => 'Quote email subject', 'type' => 'string', 'required' => false, 'default' => 'Your Quote {number} from {company}', 'max' => 255],
                'quote_email_template' => ['label' => 'Quote email template', 'type' => 'text', 'required' => false, 'default' => null],
                'invoice_email_subject' => ['label' => 'Invoice email subject', 'type' => 'string', 'required' => false, 'default' => 'Invoice {number} from {company}', 'max' => 255],
                'invoice_email_template' => ['label' => 'Invoice email template', 'type' => 'text', 'required' => false, 'default' => null],
                'followup_email_subject' => ['label' => 'Follow-up email subject', 'type' => 'string', 'required' => false, 'default' => 'Following up on Quote {number}', 'max' => 255],
                'email_footer_text' => ['label' => 'Email footer', 'type' => 'text', 'required' => false, 'default' => null],
                'include_pdf_attachment' => ['label' => 'Include PDF attachment', 'type' => 'boolean', 'required' => false, 'default' => false],
            ],
        ],
        'notifications' => [
            'label' => 'Notifications',
            'description' => 'Rules for delivery channels and digest behavior.',
            'visible' => true,
            'onboarding' => false,
            'fields' => [
                'notify_quote_viewed' => ['label' => 'Notify when quote is viewed', 'type' => 'boolean', 'required' => false, 'default' => true],
                'notify_quote_viewed_channel' => ['label' => 'Viewed channels', 'type' => 'array', 'required' => false, 'default' => ['in_app'], 'options' => ['in_app', 'mail']],
                'notify_quote_accepted' => ['label' => 'Notify when quote is accepted', 'type' => 'boolean', 'required' => false, 'default' => true],
                'notify_quote_accepted_channel' => ['label' => 'Accepted channels', 'type' => 'array', 'required' => false, 'default' => ['in_app', 'mail'], 'options' => ['in_app', 'mail']],
                'notify_quote_declined' => ['label' => 'Notify when quote is declined', 'type' => 'boolean', 'required' => false, 'default' => true],
                'notify_quote_declined_channel' => ['label' => 'Declined channels', 'type' => 'array', 'required' => false, 'default' => ['in_app', 'mail'], 'options' => ['in_app', 'mail']],
                'notify_quote_expired' => ['label' => 'Notify when quote is expired', 'type' => 'boolean', 'required' => false, 'default' => true],
                'notify_quote_sent' => ['label' => 'Notify when quote is sent', 'type' => 'boolean', 'required' => false, 'default' => true],
                'notify_quote_sent_channel' => ['label' => 'Quote sent channels', 'type' => 'array', 'required' => false, 'default' => ['in_app'], 'options' => ['in_app', 'mail']],
                'notify_invoice_sent' => ['label' => 'Notify when invoice is sent', 'type' => 'boolean', 'required' => false, 'default' => true],
                'notify_invoice_sent_channel' => ['label' => 'Invoice sent channels', 'type' => 'array', 'required' => false, 'default' => ['in_app', 'mail'], 'options' => ['in_app', 'mail']],
                'notify_follow_up_due' => ['label' => 'Notify when follow-up is due', 'type' => 'boolean', 'required' => false, 'default' => true],
                'notify_follow_up_sent' => ['label' => 'Notify when follow-up is sent', 'type' => 'boolean', 'required' => false, 'default' => true],
                'notify_follow_up_sent_channel' => ['label' => 'Follow-up sent channels', 'type' => 'array', 'required' => false, 'default' => ['in_app', 'mail'], 'options' => ['in_app', 'mail']],
                'notify_approval_requested' => ['label' => 'Notify when approval is requested', 'type' => 'boolean', 'required' => false, 'default' => true],
                'notify_approval_requested_channel' => ['label' => 'Approval requested channels', 'type' => 'array', 'required' => false, 'default' => ['in_app', 'mail'], 'options' => ['in_app', 'mail']],
                'notify_approval_approved' => ['label' => 'Notify when approval is approved', 'type' => 'boolean', 'required' => false, 'default' => true],
                'notify_approval_approved_channel' => ['label' => 'Approval approved channels', 'type' => 'array', 'required' => false, 'default' => ['in_app', 'mail'], 'options' => ['in_app', 'mail']],
                'notify_approval_granted' => ['label' => 'Notify when all approvals are granted', 'type' => 'boolean', 'required' => false, 'default' => true],
                'notify_approval_granted_channel' => ['label' => 'Approval granted channels', 'type' => 'array', 'required' => false, 'default' => ['in_app', 'mail'], 'options' => ['in_app', 'mail']],
                'notify_approval_rejected' => ['label' => 'Notify when approval is rejected', 'type' => 'boolean', 'required' => false, 'default' => true],
                'notify_approval_rejected_channel' => ['label' => 'Approval rejected channels', 'type' => 'array', 'required' => false, 'default' => ['in_app', 'mail'], 'options' => ['in_app', 'mail']],
                'notify_deposit_paid' => ['label' => 'Notify when deposit is paid', 'type' => 'boolean', 'required' => false, 'default' => true],
                'digest_frequency' => ['label' => 'Digest frequency', 'type' => 'select', 'required' => false, 'default' => 'daily', 'options' => ['realtime', 'daily', 'weekly', 'off']],
                'digest_time' => ['label' => 'Digest time', 'type' => 'string', 'required' => false, 'default' => '08:00', 'max' => 5],
                'hot_lead_threshold' => ['label' => 'Hot lead threshold', 'type' => 'integer', 'required' => false, 'default' => 3, 'min' => 1, 'max' => 50],
                'viewed_notify_throttle_minutes' => ['label' => 'Viewed notify throttle minutes', 'type' => 'integer', 'required' => false, 'default' => 60, 'min' => 1, 'max' => 1440],
            ],
        ],
        'localization' => [
            'label' => 'Localization',
            'description' => 'Locale, timezone, and formatting defaults.',
            'visible' => true,
            'onboarding' => false,
            'fields' => [
                'timezone' => ['label' => 'Timezone', 'type' => 'timezone', 'required' => false, 'default' => 'UTC'],
                'date_format' => ['label' => 'Date format', 'type' => 'select', 'required' => false, 'default' => 'MMM D, YYYY', 'options' => ['MMM D, YYYY', 'YYYY-MM-DD', 'DD/MM/YYYY']],
                'time_format' => ['label' => 'Time format', 'type' => 'select', 'required' => false, 'default' => '12h', 'options' => ['12h', '24h']],
                'currency_position' => ['label' => 'Currency position', 'type' => 'select', 'required' => false, 'default' => 'before', 'options' => ['before', 'after']],
                'number_format' => ['label' => 'Number format', 'type' => 'select', 'required' => false, 'default' => '1,000.00', 'options' => ['1,000.00', '1.000,00']],
                'fiscal_year_start_month' => ['label' => 'Fiscal year start month', 'type' => 'select', 'required' => false, 'default' => '1', 'options' => ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']],
            ],
        ],
    ],
];
