// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Workspace } from './workspace';
import type { Client } from './client';
import type { User } from './user';
import type { QuoteApproval } from './quote-approval';

export interface ApprovalRuleBase {
    id: number;
    threshold_value?: Nullable<number>;
    is_active: boolean;
    workspace_id: number;
    trigger_type: string;
    client_id?: Nullable<number>;
    approver_id: number;
    created_at: string;
    updated_at: string;
}

export interface ApprovalRule extends ApprovalRuleBase {
    workspace?: Workspace;
    client?: Client;
    approver?: User;
    quoteApprovals?: QuoteApproval[];
}

export type CreateApprovalRulePayload = Omit<ApprovalRuleBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateApprovalRulePayload = Partial<CreateApprovalRulePayload>;
