// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { CatalogItem } from './catalog-item';
import type { CatalogItemVariant } from './catalog-item-variant';
import type { Nullable } from './model-helpers';

export type PricingType = 'fixed_price' | 'discount_percent';

export interface CatalogItemPriceTierBase {
    id: number;
    pricing_type: PricingType;
    unit_price: number;
    discount_percent: number;
    catalog_item_id: number;
    variant_id: unknown;
    min_quantity: number;
    max_quantity?: Nullable<number>;
    created_at: string;
    updated_at: string;
}

export interface CatalogItemPriceTier extends CatalogItemPriceTierBase {
    catalogItem?: CatalogItem;
    variant?: CatalogItemVariant;
}

export type CreateCatalogItemPriceTierPayload = Omit<CatalogItemPriceTierBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateCatalogItemPriceTierPayload = Partial<CreateCatalogItemPriceTierPayload>;
