// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Workspace } from './workspace';
import type { User } from './user';
import type { CatalogItem } from './catalog-item';

export interface CatalogCategory {
    id: number;
    is_active: boolean;
    deleted_at?: Nullable<string>;
    workspace_id: number;
    name: string;
    sort_order: number;
    created_by?: Nullable<number>;
    created_at: string;
    updated_at: string;
    workspace?: Workspace;
    creator?: User;
    items?: CatalogItem[];
}

export type CreateCatalogCategoryPayload = Omit<CatalogCategory, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'workspace' | 'creator' | 'items'>;
export type UpdateCatalogCategoryPayload = Partial<CreateCatalogCategoryPayload>;
