// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { CatalogItem } from './catalog-item';

export interface CatalogItemVariant {
    id: number;
    is_default: boolean;
    unit_price: number;
    cost_price?: Nullable<number>;
    catalog_item_id: number;
    name: string;
    sku?: Nullable<string>;
    sort_order: number;
    created_at: string;
    updated_at: string;
    catalogItem?: CatalogItem;
}

export type CreateCatalogItemVariantPayload = Omit<CatalogItemVariant, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'catalogItem'>;
export type UpdateCatalogItemVariantPayload = Partial<CreateCatalogItemVariantPayload>;
