// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { CatalogItem } from './catalog-item';
import type { Nullable } from './model-helpers';

export interface CatalogItemVariantBase {
    id: number;
    is_default: boolean;
    unit_price: number;
    cost_price?: Nullable<number>;
    catalog_item_id: number;
    name: string;
    sku?: Nullable<string>;
    sort_order: number;
    created_at: string;
    updated_at: string;
}

export interface CatalogItemVariant extends CatalogItemVariantBase {
    catalogItem?: CatalogItem;
}

export type CreateCatalogItemVariantPayload = Omit<
    CatalogItemVariantBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdateCatalogItemVariantPayload =
    Partial<CreateCatalogItemVariantPayload>;
