// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { CatalogItem } from './catalog-item';
import type { Nullable } from './model-helpers';
import type { User } from './user';
import type { Workspace } from './workspace';

export interface CatalogCategoryBase {
    id: number;
    is_active: boolean;
    deleted_at?: Nullable<string>;
    workspace_id: number;
    name: string;
    sort_order: number;
    created_by?: Nullable<number>;
    created_at: string;
    updated_at: string;
}

export interface CatalogCategory extends CatalogCategoryBase {
    workspace?: Workspace;
    creator?: User;
    items?: CatalogItem[];
}

export type CreateCatalogCategoryPayload = Omit<
    CatalogCategoryBase,
    'id' | 'created_at' | 'updated_at' | 'deleted_at'
>;
export type UpdateCatalogCategoryPayload =
    Partial<CreateCatalogCategoryPayload>;
