// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Workspace } from './workspace';
import type { CatalogCategory } from './catalog-category';
import type { ConfigurationUnit } from './configuration-unit';
import type { Tax } from './tax';
import type { User } from './user';
import type { CatalogItemVariant } from './catalog-item-variant';
import type { CatalogItemPriceTier } from './catalog-item-price-tier';

export interface CatalogItem {
    id: number;
    unit_price: number;
    cost_price: number;
    is_active: boolean;
    deleted_at?: Nullable<string>;
    workspace_id: number;
    catalog_category_id?: Nullable<number>;
    name: string;
    description?: Nullable<string>;
    sku?: Nullable<string>;
    unit_id?: Nullable<number>;
    image_url: unknown;
    usage_count: number;
    created_by?: Nullable<number>;
    created_at: string;
    updated_at: string;
    workspace?: Workspace;
    category?: CatalogCategory;
    configurationUnit?: ConfigurationUnit;
    taxes?: Tax[];
    creator?: User;
    variants?: CatalogItemVariant[];
    priceTiers?: CatalogItemPriceTier[];
}

export type CreateCatalogItemPayload = Omit<CatalogItem, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'workspace' | 'category' | 'configurationUnit' | 'taxes' | 'creator' | 'variants' | 'priceTiers'>;
export type UpdateCatalogItemPayload = Partial<CreateCatalogItemPayload>;
