// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Workspace } from './workspace';
import type { User } from './user';
import type { ConfigurationTag } from './configuration-tag';
import type { Note } from './note';
import type { Contact } from './contact';
import type { Quote } from './quote';

export interface Client {
    id: number;
    deleted_at?: Nullable<string>;
    workspace_id: number;
    company_name: string;
    contact_name?: Nullable<string>;
    email?: Nullable<string>;
    phone?: Nullable<string>;
    whatsapp?: Nullable<string>;
    address?: Nullable<string>;
    city?: Nullable<string>;
    country?: Nullable<string>;
    currency?: Nullable<string>;
    language?: Nullable<string>;
    tax_number?: Nullable<string>;
    created_by?: Nullable<number>;
    primary_contact_id?: Nullable<number>;
    health_score?: Nullable<number>;
    created_at: string;
    updated_at: string;
    workspace?: Workspace;
    creator?: User;
    tags?: ConfigurationTag[];
    notes?: Note[];
    contacts?: Contact[];
    quotes?: Quote[];
    primaryContact?: Contact;
}

export type CreateClientPayload = Omit<Client, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'workspace' | 'creator' | 'tags' | 'notes' | 'contacts' | 'quotes' | 'primaryContact'>;
export type UpdateClientPayload = Partial<CreateClientPayload>;
