// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { User } from './user';
import type { Workspace } from './workspace';

export interface CommentBase {
    id: number;
    mentions: Record<string, unknown>;
    is_internal: boolean;
    workspace_id: unknown;
    user_id: unknown;
    commentable_type: unknown;
    commentable_id: unknown;
    content: unknown;
    created_at: string;
    updated_at: string;
}

export interface Comment extends CommentBase {
    user?: User;
    workspace?: Workspace;
    commentable?: unknown;
}

export type CreateCommentPayload = Omit<CommentBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateCommentPayload = Partial<CreateCommentPayload>;
