// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { User } from './user';
import type { Workspace } from './workspace';

export interface ConfigurationUnitBase {
    id: number;
    is_active: boolean;
    deleted_at?: Nullable<string>;
    workspace_id: number;
    name: string;
    symbol?: Nullable<string>;
    created_by?: Nullable<number>;
    created_at: string;
    updated_at: string;
}

export interface ConfigurationUnit extends ConfigurationUnitBase {
    workspace?: Workspace;
    creator?: User;
}

export type CreateConfigurationUnitPayload = Omit<
    ConfigurationUnitBase,
    'id' | 'created_at' | 'updated_at' | 'deleted_at'
>;
export type UpdateConfigurationUnitPayload =
    Partial<CreateConfigurationUnitPayload>;
