// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Client } from './client';
import type { Nullable } from './model-helpers';
import type { User } from './user';
import type { Workspace } from './workspace';

export interface ConfigurationTagBase {
    id: number;
    is_active: boolean;
    deleted_at?: Nullable<string>;
    workspace_id: number;
    name: string;
    created_by?: Nullable<number>;
    created_at: string;
    updated_at: string;
}

export interface ConfigurationTag extends ConfigurationTagBase {
    workspace?: Workspace;
    creator?: User;
    clients?: Client[];
}

export type CreateConfigurationTagPayload = Omit<ConfigurationTagBase, 'id' | 'created_at' | 'updated_at' | 'deleted_at'>;
export type UpdateConfigurationTagPayload = Partial<CreateConfigurationTagPayload>;
