// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { User } from './user';
import type { Workspace } from './workspace';

export interface ConfigIndustryBase {
    id: number;
    is_active: boolean;
    deleted_at?: Nullable<string>;
    workspace_id: number;
    name: string;
    description?: Nullable<string>;
    icon?: Nullable<string>;
    color?: Nullable<string>;
    created_by?: Nullable<number>;
    created_at: string;
    updated_at: string;
}

export interface ConfigIndustry extends ConfigIndustryBase {
    workspace?: Workspace;
    creator?: User;
}

export type CreateConfigIndustryPayload = Omit<
    ConfigIndustryBase,
    'id' | 'created_at' | 'updated_at' | 'deleted_at'
>;
export type UpdateConfigIndustryPayload = Partial<CreateConfigIndustryPayload>;
