// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Client } from './client';
import type { Nullable } from './model-helpers';

export interface ContactBase {
    id: number;
    is_primary: boolean;
    client_id: number;
    name: string;
    email?: Nullable<string>;
    phone?: Nullable<string>;
    position?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export interface Contact extends ContactBase {
    client?: Client;
}

export type CreateContactPayload = Omit<ContactBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateContactPayload = Partial<CreateContactPayload>;
