// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Client } from './client';

export interface Contact {
    id: number;
    is_primary: boolean;
    client_id: number;
    name: string;
    email?: Nullable<string>;
    phone?: Nullable<string>;
    position?: Nullable<string>;
    created_at: string;
    updated_at: string;
    client?: Client;
}

export type CreateContactPayload = Omit<Contact, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'client'>;
export type UpdateContactPayload = Partial<CreateContactPayload>;
