// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Client } from './client';
import type { CreditNoteLineItem } from './credit-note-line-item';
import type { Invoice } from './invoice';
import type { Nullable } from './model-helpers';
import type { User } from './user';
import type { Workspace } from './workspace';

export type CreditNoteType = 'full' | 'partial' | 'line_items';
export type CreditNoteStatus = 'draft' | 'issued' | 'applied' | 'voided';

export interface CreditNoteBase {
    id: number;
    type: CreditNoteType;
    status: CreditNoteStatus;
    subtotal: number;
    tax_amount?: Nullable<number>;
    total?: Nullable<number>;
    base_subtotal: number;
    base_tax_amount?: Nullable<number>;
    base_total?: Nullable<number>;
    issue_date?: Nullable<string>;
    due_date?: Nullable<string>;
    applied_at?: Nullable<string>;
    fx_rate: number;
    workspace_id: number;
    invoice_id: number;
    client_id?: Nullable<number>;
    created_by: number;
    credit_note_number?: Nullable<string>;
    title: string;
    reason: string;
    currency: string;
    base_currency?: Nullable<string>;
    pdf_url?: Nullable<string>;
    issued_at?: Nullable<string>;
    voided_at?: Nullable<string>;
    void_reason?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export interface CreditNote extends CreditNoteBase {
    workspace?: Workspace;
    invoice?: Invoice;
    client?: Client;
    createdBy?: User;
    lineItems?: CreditNoteLineItem[];
}

export type CreateCreditNotePayload = Omit<
    CreditNoteBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdateCreditNotePayload = Partial<CreateCreditNotePayload>;
