// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { CreditNote } from './credit-note';

export interface CreditNoteLineItem {
    id: number;
    quantity: number;
    unit_price: number;
    base_unit_price?: Nullable<number>;
    tax_amount: number;
    base_tax_amount?: Nullable<number>;
    subtotal: number;
    base_subtotal?: Nullable<number>;
    total: number;
    base_total?: Nullable<number>;
    credit_note_id: number;
    name: string;
    description?: Nullable<string>;
    unit?: Nullable<string>;
    created_at: string;
    updated_at: string;
    creditNote?: CreditNote;
}

export type CreateCreditNoteLineItemPayload = Omit<CreditNoteLineItem, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'creditNote'>;
export type UpdateCreditNoteLineItemPayload = Partial<CreateCreditNoteLineItemPayload>;
