// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';

export interface Customer {
    id: number;
    trial_ends_at?: Nullable<string>;
    created_at: string;
    updated_at: string;
    billable?: unknown;
}

export type CreateCustomerPayload = Omit<Customer, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'billable'>;
export type UpdateCustomerPayload = Partial<CreateCustomerPayload>;
