// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Workspace } from './workspace';

export interface CustomDomain {
    id: number;
    verified_at?: Nullable<string>;
    is_primary: boolean;
    is_active: boolean;
    workspace_id: number;
    domain: string;
    verification_token?: Nullable<string>;
    created_at: string;
    updated_at: string;
    workspace?: Workspace;
}

export type CreateCustomDomainPayload = Omit<CustomDomain, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'workspace'>;
export type UpdateCustomDomainPayload = Partial<CreateCustomDomainPayload>;
