// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';

export interface CustomerBase {
    id: number;
    trial_ends_at?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export interface Customer extends CustomerBase {
    billable?: unknown;
}

export type CreateCustomerPayload = Omit<
    CustomerBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdateCustomerPayload = Partial<CreateCustomerPayload>;
