// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';

export interface DatabaseNotification {
    data: Record<string, unknown>;
    read_at?: Nullable<string>;
    created_at: string;
    updated_at: string;
    notifiable?: unknown;
}

export type CreateDatabaseNotificationPayload = Omit<DatabaseNotification, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'notifiable'>;
export type UpdateDatabaseNotificationPayload = Partial<CreateDatabaseNotificationPayload>;
