// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { FollowUpSequence } from './follow-up-sequence';
import type { QuoteFollowUp } from './quote-follow-up';

export type FollowUpChannel = 'email' | 'whatsapp' | 'sms';

export interface FollowUpStep {
    id: number;
    day_offset: number;
    channel: FollowUpChannel;
    sort_order: number;
    follow_up_sequence_id: number;
    subject?: Nullable<string>;
    message_template: string;
    created_at: string;
    updated_at: string;
    sequence?: FollowUpSequence;
    quoteFollowUps?: QuoteFollowUp[];
}

export type CreateFollowUpStepPayload = Omit<FollowUpStep, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'sequence' | 'quoteFollowUps'>;
export type UpdateFollowUpStepPayload = Partial<CreateFollowUpStepPayload>;
