// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Workspace } from './workspace';
import type { FollowUpStep } from './follow-up-step';

export interface FollowUpSequence {
    id: number;
    is_default: boolean;
    workspace_id: number;
    name: string;
    created_at: string;
    updated_at: string;
    workspace?: Workspace;
    steps?: FollowUpStep[];
}

export type CreateFollowUpSequencePayload = Omit<FollowUpSequence, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'workspace' | 'steps'>;
export type UpdateFollowUpSequencePayload = Partial<CreateFollowUpSequencePayload>;
