// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { FollowUpStep } from './follow-up-step';
import type { Workspace } from './workspace';

export interface FollowUpSequenceBase {
    id: number;
    is_default: boolean;
    workspace_id: number;
    name: string;
    created_at: string;
    updated_at: string;
}

export interface FollowUpSequence extends FollowUpSequenceBase {
    workspace?: Workspace;
    steps?: FollowUpStep[];
}

export type CreateFollowUpSequencePayload = Omit<
    FollowUpSequenceBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdateFollowUpSequencePayload =
    Partial<CreateFollowUpSequencePayload>;
