// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { User } from './user';
import type { Workspace } from './workspace';

export interface ImportHistoryBase {
    id: number;
    error_details?: Nullable<Record<string, unknown>>;
    started_at?: Nullable<string>;
    completed_at?: Nullable<string>;
    workspace_id: number;
    user_id: number;
    type: string;
    status: string;
    total_rows: number;
    processed_rows: number;
    failed_rows: number;
    created_at: string;
    updated_at: string;
}

export interface ImportHistory extends ImportHistoryBase {
    workspace?: Workspace;
    user?: User;
}

export type CreateImportHistoryPayload = Omit<
    ImportHistoryBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdateImportHistoryPayload = Partial<CreateImportHistoryPayload>;
