// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';

export interface Industry {
    id: number;
    is_active: boolean;
    name: string;
    description?: Nullable<string>;
    icon?: Nullable<string>;
    color?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export type CreateIndustryPayload = Omit<Industry, 'id' | 'created_at' | 'updated_at' | 'deleted_at'>;
export type UpdateIndustryPayload = Partial<CreateIndustryPayload>;
