// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Role } from './role';
import type { User } from './user';
import type { Workspace } from './workspace';

export interface InvitationBase {
    id: number;
    expires_at?: Nullable<string>;
    accepted_at?: Nullable<string>;
    workspace_id: number;
    email: string;
    role_id?: Nullable<number>;
    invited_by: number;
    created_at: string;
    updated_at: string;
}

export interface Invitation extends InvitationBase {
    workspace?: Workspace;
    role?: Role;
    inviter?: User;
}

export type CreateInvitationPayload = Omit<
    InvitationBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdateInvitationPayload = Partial<CreateInvitationPayload>;
