// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Workspace } from './workspace';
import type { Role } from './role';
import type { User } from './user';

export interface Invitation {
    id: number;
    expires_at?: Nullable<string>;
    accepted_at?: Nullable<string>;
    workspace_id: number;
    email: string;
    role_id?: Nullable<number>;
    invited_by: number;
    created_at: string;
    updated_at: string;
    workspace?: Workspace;
    role?: Role;
    inviter?: User;
}

export type CreateInvitationPayload = Omit<Invitation, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'workspace' | 'role' | 'inviter'>;
export type UpdateInvitationPayload = Partial<CreateInvitationPayload>;
