// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Invoice } from './invoice';
import type { InvoiceReminderStep } from './invoice-reminder-step';
import type { Nullable } from './model-helpers';
import type { Workspace } from './workspace';

export interface InvoiceReminderBase {
    id: number;
    scheduled_at: string;
    sent_at?: Nullable<string>;
    invoice_id: number;
    workspace_id: number;
    invoice_reminder_step_id?: Nullable<number>;
    reminder_type: string;
    days_offset?: Nullable<number>;
    channel: string;
    status: string;
    error_message?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export interface InvoiceReminder extends InvoiceReminderBase {
    invoice?: Invoice;
    workspace?: Workspace;
    step?: InvoiceReminderStep;
}

export type CreateInvoiceReminderPayload = Omit<
    InvoiceReminderBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdateInvoiceReminderPayload =
    Partial<CreateInvoiceReminderPayload>;
