// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Invoice } from './invoice';
import type { Workspace } from './workspace';
import type { InvoiceReminderStep } from './invoice-reminder-step';

export interface InvoiceReminder {
    id: number;
    scheduled_at: string;
    sent_at?: Nullable<string>;
    invoice_id: number;
    workspace_id: number;
    invoice_reminder_step_id?: Nullable<number>;
    reminder_type: string;
    days_offset?: Nullable<number>;
    channel: string;
    status: string;
    error_message?: Nullable<string>;
    created_at: string;
    updated_at: string;
    invoice?: Invoice;
    workspace?: Workspace;
    step?: InvoiceReminderStep;
}

export type CreateInvoiceReminderPayload = Omit<InvoiceReminder, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'invoice' | 'workspace' | 'step'>;
export type UpdateInvoiceReminderPayload = Partial<CreateInvoiceReminderPayload>;
