// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Invoice } from './invoice';
import type { Nullable } from './model-helpers';
import type { User } from './user';
import type { Workspace } from './workspace';

export interface InvoicePaymentBase {
    id: number;
    amount: number;
    payment_date: string;
    refunded_at?: Nullable<string>;
    is_refund: boolean;
    workspace_id: number;
    invoice_id: number;
    created_by?: Nullable<number>;
    currency: string;
    payment_method?: Nullable<string>;
    reference_number?: Nullable<string>;
    notes?: Nullable<string>;
    refund_reason?: Nullable<string>;
    refunded_by?: Nullable<number>;
    created_at: string;
    updated_at: string;
}

export interface InvoicePayment extends InvoicePaymentBase {
    invoice?: Invoice;
    workspace?: Workspace;
    refundedBy?: User;
    createdBy?: User;
}

export type CreateInvoicePaymentPayload = Omit<
    InvoicePaymentBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdateInvoicePaymentPayload = Partial<CreateInvoicePaymentPayload>;
