// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { InvoiceLineItem } from './invoice-line-item';
import type { Nullable } from './model-helpers';
import type { Tax } from './tax';

export interface InvoiceLineItemTaxBase {
    id: number;
    tax_rate: number;
    inclusive: boolean;
    tax_amount: number;
    base_tax_amount: number;
    invoice_line_item_id: number;
    tax_id?: Nullable<number>;
    tax_label: string;
    created_at: string;
    updated_at: string;
}

export interface InvoiceLineItemTax extends InvoiceLineItemTaxBase {
    lineItem?: InvoiceLineItem;
    tax?: Tax;
}

export type CreateInvoiceLineItemTaxPayload = Omit<InvoiceLineItemTaxBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateInvoiceLineItemTaxPayload = Partial<CreateInvoiceLineItemTaxPayload>;
