// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { InvoiceReminderStep } from './invoice-reminder-step';
import type { Workspace } from './workspace';

export interface InvoiceReminderSequenceBase {
    id: number;
    is_default: boolean;
    workspace_id: number;
    name: string;
    created_at: string;
    updated_at: string;
}

export interface InvoiceReminderSequence extends InvoiceReminderSequenceBase {
    workspace?: Workspace;
    steps?: InvoiceReminderStep[];
}

export type CreateInvoiceReminderSequencePayload = Omit<
    InvoiceReminderSequenceBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdateInvoiceReminderSequencePayload =
    Partial<CreateInvoiceReminderSequencePayload>;
