// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Invoice } from './invoice';
import type { Workspace } from './workspace';
import type { User } from './user';

export interface InvoiceActivity {
    id: number;
    metadata?: Nullable<Record<string, unknown>>;
    invoice_id: number;
    workspace_id: number;
    user_id?: Nullable<number>;
    type: string;
    description: string;
    ip_address?: Nullable<string>;
    user_agent?: Nullable<string>;
    created_at: string;
    updated_at: string;
    invoice?: Invoice;
    workspace?: Workspace;
    user?: User;
}

export type CreateInvoiceActivityPayload = Omit<InvoiceActivity, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'invoice' | 'workspace' | 'user'>;
export type UpdateInvoiceActivityPayload = Partial<CreateInvoiceActivityPayload>;
