// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Invoice } from './invoice';
import type { InvoiceLineItem } from './invoice-line-item';

export interface InvoiceSection {
    id: number;
    invoice_id: number;
    title: string;
    sort_order: number;
    created_at: string;
    updated_at: string;
    invoice?: Invoice;
    lineItems?: InvoiceLineItem[];
}

export type CreateInvoiceSectionPayload = Omit<InvoiceSection, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'invoice' | 'lineItems'>;
export type UpdateInvoiceSectionPayload = Partial<CreateInvoiceSectionPayload>;
