// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { CatalogItem } from './catalog-item';
import type { CatalogItemVariant } from './catalog-item-variant';
import type { Invoice } from './invoice';
import type { InvoiceLineItemTax } from './invoice-line-item-tax';
import type { InvoiceSection } from './invoice-section';
import type { Nullable } from './model-helpers';
import type { PriceTier } from './price-tier';

export type DiscountType = 'percent' | 'fixed';

export interface InvoiceLineItemBase {
    id: number;
    quantity: number;
    unit_price: number;
    base_unit_price?: Nullable<number>;
    tax_rate: number;
    discount_type?: Nullable<DiscountType>;
    discount_value?: Nullable<number>;
    subtotal?: Nullable<number>;
    base_subtotal?: Nullable<number>;
    tax_amount?: Nullable<number>;
    base_tax_amount?: Nullable<number>;
    total: number;
    base_total?: Nullable<number>;
    invoice_id: number;
    invoice_section_id?: Nullable<number>;
    catalog_item_id?: Nullable<number>;
    catalog_item_variant_id?: Nullable<number>;
    name: string;
    description?: Nullable<string>;
    unit?: Nullable<string>;
    sort_order: number;
    created_at: string;
    updated_at: string;
}

export interface InvoiceLineItem extends InvoiceLineItemBase {
    invoice?: Invoice;
    section?: InvoiceSection;
    catalogItem?: CatalogItem;
    catalogItemVariant?: CatalogItemVariant;
    taxes?: InvoiceLineItemTax[];
    priceTiers?: PriceTier[];
}

export type CreateInvoiceLineItemPayload = Omit<
    InvoiceLineItemBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdateInvoiceLineItemPayload =
    Partial<CreateInvoiceLineItemPayload>;
