// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Workspace } from './workspace';
import type { Client } from './client';
import type { Quote } from './quote';
import type { User } from './user';
import type { InvoiceLineItem } from './invoice-line-item';
import type { InvoiceSection } from './invoice-section';
import type { InvoiceActivity } from './invoice-activity';
import type { Comment } from './comment';
import type { InvoicePayment } from './invoice-payment';
import type { RecurringInvoice } from './recurring-invoice';
import type { CreditNote } from './credit-note';
import type { InvoiceReminder } from './invoice-reminder';

export type InvoiceStatus = 'draft' | 'sent' | 'partial' | 'paid' | 'overdue' | 'void';

export interface Invoice {
    id: number;
    status: InvoiceStatus;
    layout_snapshot?: Nullable<Record<string, unknown>>;
    subtotal: number;
    tax_amount: number;
    discount_amount: number;
    total: number;
    base_subtotal?: Nullable<number>;
    base_tax_amount?: Nullable<number>;
    base_discount_amount?: Nullable<number>;
    base_total?: Nullable<number>;
    paid_amount: number;
    amount_credited: number;
    balance_due: number;
    fx_rate?: Nullable<number>;
    issue_date?: Nullable<string>;
    due_date?: Nullable<string>;
    paid_date?: Nullable<string>;
    sent_at?: Nullable<string>;
    deleted_at?: Nullable<string>;
    workspace_id: number;
    invoice_uuid?: Nullable<string>;
    client_id: number;
    quote_id?: Nullable<number>;
    recurring_invoice_id?: Nullable<number>;
    invoice_number: string;
    title: string;
    cover_message?: Nullable<string>;
    terms?: Nullable<string>;
    notes?: Nullable<string>;
    currency: string;
    base_currency?: Nullable<string>;
    created_by?: Nullable<number>;
    pdf_url?: Nullable<string>;
    created_at: string;
    updated_at: string;
    workspace?: Workspace;
    client?: Client;
    quote?: Quote;
    createdBy?: User;
    lineItems?: InvoiceLineItem[];
    sections?: InvoiceSection[];
    activities?: InvoiceActivity[];
    comments?: Comment[];
    payments?: InvoicePayment[];
    recurringInvoice?: RecurringInvoice;
    creditNotes?: CreditNote[];
    reminders?: InvoiceReminder[];
}

export type CreateInvoicePayload = Omit<Invoice, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'workspace' | 'client' | 'quote' | 'createdBy' | 'lineItems' | 'sections' | 'activities' | 'comments' | 'payments' | 'recurringInvoice' | 'creditNotes' | 'reminders'>;
export type UpdateInvoicePayload = Partial<CreateInvoicePayload>;
