// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Workspace } from './workspace';
import type { InvoiceReminderStep } from './invoice-reminder-step';

export interface InvoiceReminderSequence {
    id: number;
    is_default: boolean;
    workspace_id: number;
    name: string;
    created_at: string;
    updated_at: string;
    workspace?: Workspace;
    steps?: InvoiceReminderStep[];
}

export type CreateInvoiceReminderSequencePayload = Omit<InvoiceReminderSequence, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'workspace' | 'steps'>;
export type UpdateInvoiceReminderSequencePayload = Partial<CreateInvoiceReminderSequencePayload>;
