// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { InvoiceReminder } from './invoice-reminder';
import type { InvoiceReminderSequence } from './invoice-reminder-sequence';

export type FollowUpChannel = 'email' | 'whatsapp' | 'sms';
export type InvoiceReminderType = 'before_due' | 'on_due' | 'after_due';

export interface InvoiceReminderStepBase {
    id: number;
    day_offset: number;
    channel: FollowUpChannel;
    reminder_type: InvoiceReminderType;
    send_automatically: boolean;
    sort_order: number;
    invoice_reminder_sequence_id: number;
    subject: string;
    message_template: string;
    created_at: string;
    updated_at: string;
}

export interface InvoiceReminderStep extends InvoiceReminderStepBase {
    sequence?: InvoiceReminderSequence;
    invoiceReminders?: InvoiceReminder[];
}

export type CreateInvoiceReminderStepPayload = Omit<InvoiceReminderStepBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateInvoiceReminderStepPayload = Partial<CreateInvoiceReminderStepPayload>;
