// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Workspace } from './workspace';
import type { User } from './user';

export interface NoteBase {
    id: number;
    deleted_at?: Nullable<string>;
    workspace_id: number;
    content: string;
    noteable_type: unknown;
    noteable_id: unknown;
    created_by?: Nullable<number>;
    created_at: string;
    updated_at: string;
}

export interface Note extends NoteBase {
    noteable?: unknown;
    workspace?: Workspace;
    creator?: User;
}

export type CreateNotePayload = Omit<NoteBase, 'id' | 'created_at' | 'updated_at' | 'deleted_at'>;
export type UpdateNotePayload = Partial<CreateNotePayload>;
