// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';

export interface Permission {
    id: number;
    name: string;
    display_name?: Nullable<string>;
    description?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export type CreatePermissionPayload = Omit<Permission, 'id' | 'created_at' | 'updated_at' | 'deleted_at'>;
export type UpdatePermissionPayload = Partial<CreatePermissionPayload>;
