// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';

export interface PermissionBase {
    id: number;
    name: string;
    display_name?: Nullable<string>;
    description?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export type Permission = PermissionBase;

export type CreatePermissionPayload = Omit<PermissionBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdatePermissionPayload = Partial<CreatePermissionPayload>;
