// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Workspace } from './workspace';

export interface PlanBase {
    id: number;
    features?: Nullable<Record<string, unknown>>;
    monthly_price?: Nullable<number>;
    yearly_price?: Nullable<number>;
    is_active: boolean;
    slug: string;
    name: string;
    description?: Nullable<string>;
    paddle_monthly_price_id?: Nullable<string>;
    paddle_yearly_price_id?: Nullable<string>;
    sort_order: number;
    created_at: string;
    updated_at: string;
}

export interface Plan extends PlanBase {
    workspaces?: Workspace[];
}

export type CreatePlanPayload = Omit<PlanBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdatePlanPayload = Partial<CreatePlanPayload>;
