// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Workspace } from './workspace';
import type { Client } from './client';
import type { Quote } from './quote';
import type { DatabaseNotification } from './database-notification';

export interface PortalUserBase {
    id: number;
    email_verified_at?: Nullable<string>;
    workspace_id: number;
    client_id?: Nullable<number>;
    name: string;
    email: string;
    created_at: string;
    updated_at: string;
}

export interface PortalUser extends PortalUserBase {
    workspace?: Workspace;
    client?: Client;
    quotes?: Quote[];
    notifications?: DatabaseNotification[];
    readNotifications?: DatabaseNotification[];
    unreadNotifications?: DatabaseNotification[];
}

export type CreatePortalUserPayload = Omit<PortalUserBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdatePortalUserPayload = Partial<CreatePortalUserPayload>;
