// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Workspace } from './workspace';
import type { Client } from './client';

export interface PortalInvitationBase {
    id: number;
    expires_at: string;
    accepted_at?: Nullable<string>;
    workspace_id: number;
    client_id?: Nullable<number>;
    email: string;
    token: string;
    created_at: string;
    updated_at: string;
}

export interface PortalInvitation extends PortalInvitationBase {
    workspace?: Workspace;
    client?: Client;
}

export type CreatePortalInvitationPayload = Omit<PortalInvitationBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdatePortalInvitationPayload = Partial<CreatePortalInvitationPayload>;
