// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { CatalogItemVariant } from './catalog-item-variant';
import type { Nullable } from './model-helpers';

export interface PriceTierBase {
    id: number;
    min_quantity: number;
    max_quantity: number;
    unit_price?: Nullable<number>;
    discount_percent?: Nullable<number>;
    priceable_id: number;
    priceable_type: string;
    variant_id?: Nullable<number>;
    pricing_type: string;
    created_at: string;
    updated_at: string;
}

export interface PriceTier extends PriceTierBase {
    priceable?: unknown;
    variant?: CatalogItemVariant;
}

export type CreatePriceTierPayload = Omit<
    PriceTierBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdatePriceTierPayload = Partial<CreatePriceTierPayload>;
