// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { ApprovalRule } from './approval-rule';
import type { Nullable } from './model-helpers';
import type { Quote } from './quote';
import type { User } from './user';

export interface QuoteApprovalBase {
    id: number;
    approved_at?: Nullable<string>;
    quote_id: number;
    approval_rule_id: number;
    approver_id: number;
    status: string;
    comment?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export interface QuoteApproval extends QuoteApprovalBase {
    quote?: Quote;
    approvalRule?: ApprovalRule;
    approver?: User;
}

export type CreateQuoteApprovalPayload = Omit<QuoteApprovalBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateQuoteApprovalPayload = Partial<CreateQuoteApprovalPayload>;
