// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Quote } from './quote';
import type { User } from './user';
import type { Workspace } from './workspace';

export interface QuoteActivityBase {
    id: number;
    metadata?: Nullable<Record<string, unknown>>;
    quote_id: number;
    workspace_id: number;
    user_id?: Nullable<number>;
    type: string;
    description: string;
    ip_address?: Nullable<string>;
    user_agent?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export interface QuoteActivity extends QuoteActivityBase {
    quote?: Quote;
    workspace?: Workspace;
    user?: User;
}

export type CreateQuoteActivityPayload = Omit<QuoteActivityBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateQuoteActivityPayload = Partial<CreateQuoteActivityPayload>;
