// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Quote } from './quote';
import type { QuoteWinProbabilitySignal } from './quote-win-probability-signal';

export type WinProbabilityConfidence = 'none' | 'low' | 'medium' | 'high';

export interface QuoteWinProbability {
    id: number;
    probability?: Nullable<number>;
    confidence: WinProbabilityConfidence;
    has_data: boolean;
    quote_id: number;
    created_at: string;
    updated_at: string;
    quote?: Quote;
    signals?: QuoteWinProbabilitySignal[];
}

export type CreateQuoteWinProbabilityPayload = Omit<QuoteWinProbability, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'quote' | 'signals'>;
export type UpdateQuoteWinProbabilityPayload = Partial<CreateQuoteWinProbabilityPayload>;
