// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Quote } from './quote';
import type { User } from './user';
import type { PortalUser } from './portal-user';

export interface QuoteMessage {
    id: number;
    is_internal: boolean;
    quote_id: number;
    sender_id?: Nullable<number>;
    portal_user_id?: Nullable<number>;
    message: string;
    sender_type: string;
    created_at: string;
    updated_at: string;
    quote?: Quote;
    sender?: User;
    portalUser?: PortalUser;
}

export type CreateQuoteMessagePayload = Omit<QuoteMessage, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'quote' | 'sender' | 'portalUser'>;
export type UpdateQuoteMessagePayload = Partial<CreateQuoteMessagePayload>;
