// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Quote } from './quote';

export type TrackingEventType = 'view' | 'section_visible' | 'scroll_depth' | 'time_spent' | 'link_click';

export interface QuoteTrackingEvent {
    id: number;
    event_type: TrackingEventType;
    duration_seconds: number;
    scroll_depth_percent: number;
    metadata?: Nullable<Record<string, unknown>>;
    occurred_at: string;
    quote_id: number;
    section_name?: Nullable<string>;
    ip_address?: Nullable<string>;
    user_agent?: Nullable<string>;
    quote?: Quote;
}

export type CreateQuoteTrackingEventPayload = Omit<QuoteTrackingEvent, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'quote'>;
export type UpdateQuoteTrackingEventPayload = Partial<CreateQuoteTrackingEventPayload>;
