// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { CatalogItem } from './catalog-item';
import type { Nullable } from './model-helpers';
import type { QuoteTemplate } from './quote-template';
import type { QuoteTemplateLineItemTax } from './quote-template-line-item-tax';
import type { QuoteTemplateSection } from './quote-template-section';

export interface QuoteTemplateLineItemBase {
    id: number;
    quantity: number;
    unit_price: number;
    discount_percent: number;
    is_optional: boolean;
    quote_template_id: number;
    quote_template_section_id: number;
    catalog_item_id?: Nullable<number>;
    name: string;
    description?: Nullable<string>;
    unit?: Nullable<string>;
    notes?: Nullable<string>;
    sort_order: number;
    created_at: string;
    updated_at: string;
}

export interface QuoteTemplateLineItem extends QuoteTemplateLineItemBase {
    template?: QuoteTemplate;
    section?: QuoteTemplateSection;
    catalogItem?: CatalogItem;
    taxes?: QuoteTemplateLineItemTax[];
}

export type CreateQuoteTemplateLineItemPayload = Omit<QuoteTemplateLineItemBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateQuoteTemplateLineItemPayload = Partial<CreateQuoteTemplateLineItemPayload>;
