// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Quote } from './quote';
import type { FollowUpStep } from './follow-up-step';

export type QuoteFollowUpStatus = 'pending' | 'sent' | 'cancelled';

export interface QuoteFollowUpBase {
    id: number;
    status: QuoteFollowUpStatus;
    scheduled_at: string;
    sent_at?: Nullable<string>;
    cancelled_at?: Nullable<string>;
    quote_id: number;
    follow_up_step_id: number;
    created_at: string;
    updated_at: string;
}

export interface QuoteFollowUp extends QuoteFollowUpBase {
    quote?: Quote;
    step?: FollowUpStep;
}

export type CreateQuoteFollowUpPayload = Omit<QuoteFollowUpBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateQuoteFollowUpPayload = Partial<CreateQuoteFollowUpPayload>;
