// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { QuoteTemplate } from './quote-template';
import type { QuoteTemplateLineItem } from './quote-template-line-item';

export interface QuoteTemplateSection {
    id: number;
    quote_template_id: number;
    title: string;
    sort_order: number;
    created_at: string;
    updated_at: string;
    template?: QuoteTemplate;
    lineItems?: QuoteTemplateLineItem[];
}

export type CreateQuoteTemplateSectionPayload = Omit<QuoteTemplateSection, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'template' | 'lineItems'>;
export type UpdateQuoteTemplateSectionPayload = Partial<CreateQuoteTemplateSectionPayload>;
