// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { PortalUser } from './portal-user';
import type { Quote } from './quote';
import type { User } from './user';

export interface QuoteMessageBase {
    id: number;
    is_internal: boolean;
    quote_id: number;
    sender_id?: Nullable<number>;
    portal_user_id?: Nullable<number>;
    message: string;
    sender_type: string;
    created_at: string;
    updated_at: string;
}

export interface QuoteMessage extends QuoteMessageBase {
    quote?: Quote;
    sender?: User;
    portalUser?: PortalUser;
}

export type CreateQuoteMessagePayload = Omit<
    QuoteMessageBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdateQuoteMessagePayload = Partial<CreateQuoteMessagePayload>;
