// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { QuoteLineItem } from './quote-line-item';
import type { Tax } from './tax';

export interface QuoteLineItemTax {
    id: number;
    tax_rate: number;
    inclusive: boolean;
    tax_amount: number;
    base_tax_amount: number;
    quote_line_item_id: number;
    tax_id?: Nullable<number>;
    tax_label: string;
    created_at: string;
    updated_at: string;
    lineItem?: QuoteLineItem;
    tax?: Tax;
}

export type CreateQuoteLineItemTaxPayload = Omit<QuoteLineItemTax, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'lineItem' | 'tax'>;
export type UpdateQuoteLineItemTaxPayload = Partial<CreateQuoteLineItemTaxPayload>;
