// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { QuoteWinProbability } from './quote-win-probability';

export type SignalDirection = 'positive' | 'negative';

export interface QuoteWinProbabilitySignalBase {
    id: number;
    probability?: Nullable<number>;
    weight?: Nullable<number>;
    sample_size: number;
    direction: SignalDirection;
    meta?: Nullable<Record<string, unknown>>;
    win_probability_id: number;
    key: string;
    label: string;
    created_at: string;
    updated_at: string;
}

export interface QuoteWinProbabilitySignal extends QuoteWinProbabilitySignalBase {
    winProbability?: QuoteWinProbability;
}

export type CreateQuoteWinProbabilitySignalPayload = Omit<
    QuoteWinProbabilitySignalBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdateQuoteWinProbabilitySignalPayload =
    Partial<CreateQuoteWinProbabilitySignalPayload>;
