// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Quote } from './quote';
import type { QuoteSection } from './quote-section';
import type { CatalogItem } from './catalog-item';
import type { CatalogItemVariant } from './catalog-item-variant';
import type { QuoteLineItemTax } from './quote-line-item-tax';

export interface QuoteLineItem {
    id: number;
    quantity: number;
    unit_price: number;
    cost_price?: Nullable<number>;
    discount_percent: number;
    subtotal: number;
    total: number;
    is_optional: boolean;
    quote_id: number;
    quote_section_id: number;
    catalog_item_id?: Nullable<number>;
    catalog_item_variant_id?: Nullable<number>;
    name: string;
    description?: Nullable<string>;
    unit?: Nullable<string>;
    price_tier_applied: boolean;
    base_unit_price: number;
    base_subtotal: number;
    tax_amount: number;
    base_tax_amount: number;
    base_total: number;
    notes?: Nullable<string>;
    sort_order: number;
    created_at: string;
    updated_at: string;
    quote?: Quote;
    section?: QuoteSection;
    catalogItem?: CatalogItem;
    catalogItemVariant?: CatalogItemVariant;
    taxes?: QuoteLineItemTax[];
}

export type CreateQuoteLineItemPayload = Omit<QuoteLineItem, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'quote' | 'section' | 'catalogItem' | 'catalogItemVariant' | 'taxes'>;
export type UpdateQuoteLineItemPayload = Partial<CreateQuoteLineItemPayload>;
