// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { QuoteTemplateLineItem } from './quote-template-line-item';
import type { Tax } from './tax';

export interface QuoteTemplateLineItemTax {
    id: number;
    tax_rate: number;
    inclusive: boolean;
    quote_template_line_item_id: number;
    tax_id?: Nullable<number>;
    tax_label: string;
    created_at: string;
    updated_at: string;
    lineItem?: QuoteTemplateLineItem;
    tax?: Tax;
}

export type CreateQuoteTemplateLineItemTaxPayload = Omit<QuoteTemplateLineItemTax, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'lineItem' | 'tax'>;
export type UpdateQuoteTemplateLineItemTaxPayload = Partial<CreateQuoteTemplateLineItemTaxPayload>;
