// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Quote } from './quote';
import type { FollowUpStep } from './follow-up-step';

export type QuoteFollowUpStatus = 'pending' | 'sent' | 'cancelled';

export interface QuoteFollowUp {
    id: number;
    status: QuoteFollowUpStatus;
    scheduled_at: string;
    sent_at?: Nullable<string>;
    cancelled_at?: Nullable<string>;
    quote_id: number;
    follow_up_step_id: number;
    created_at: string;
    updated_at: string;
    quote?: Quote;
    step?: FollowUpStep;
}

export type CreateQuoteFollowUpPayload = Omit<QuoteFollowUp, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'quote' | 'step'>;
export type UpdateQuoteFollowUpPayload = Partial<CreateQuoteFollowUpPayload>;
