// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Quote } from './quote';

export interface QuoteShortCode {
    id: number;
    quote_id: number;
    code: string;
    created_at: string;
    updated_at: string;
    quote?: Quote;
}

export type CreateQuoteShortCodePayload = Omit<QuoteShortCode, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'quote'>;
export type UpdateQuoteShortCodePayload = Partial<CreateQuoteShortCodePayload>;
