// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Client } from './client';
import type { Comment } from './comment';
import type { Invoice } from './invoice';
import type { Nullable } from './model-helpers';
import type { QuoteActivity } from './quote-activity';
import type { QuoteApproval } from './quote-approval';
import type { QuoteFollowUp } from './quote-follow-up';
import type { QuoteLineItem } from './quote-line-item';
import type { QuoteMessage } from './quote-message';
import type { QuoteSection } from './quote-section';
import type { QuoteShortCode } from './quote-short-code';
import type { QuoteTemplate } from './quote-template';
import type { QuoteTrackingEvent } from './quote-tracking-event';
import type { QuoteWinProbability } from './quote-win-probability';
import type { Task } from './task';
import type { User } from './user';
import type { Workspace } from './workspace';

export type QuoteStatus = 'draft' | 'sent' | 'viewed' | 'accepted' | 'declined' | 'won' | 'lost' | 'expired' | 'pending_approval';

export interface QuoteBase {
    id: number;
    status: QuoteStatus;
    valid_until?: Nullable<string>;
    layout_snapshot?: Nullable<Record<string, unknown>>;
    subtotal: number;
    discount_amount: number;
    tax_amount: number;
    total: number;
    fx_rate?: Nullable<number>;
    base_total?: Nullable<number>;
    base_subtotal: number;
    base_discount_amount: number;
    base_tax_amount: number;
    requires_deposit: boolean;
    deposit_amount?: Nullable<number>;
    approval_granted: boolean;
    approval_granted_at?: Nullable<string>;
    sent_at?: Nullable<string>;
    viewed_at?: Nullable<string>;
    accepted_at?: Nullable<string>;
    declined_at?: Nullable<string>;
    won_at?: Nullable<string>;
    lost_at?: Nullable<string>;
    scheduled_at?: Nullable<string>;
    delivered_at?: Nullable<string>;
    bounced_at?: Nullable<string>;
    is_locked: boolean;
    cc_recipients?: Nullable<Record<string, unknown>>;
    bcc_recipients?: Nullable<Record<string, unknown>>;
    deleted_at?: Nullable<string>;
    workspace_id: number;
    quote_uuid?: Nullable<string>;
    number?: Nullable<string>;
    title: string;
    client_id?: Nullable<number>;
    assigned_to?: Nullable<number>;
    currency?: Nullable<string>;
    base_currency?: Nullable<string>;
    cover_message?: Nullable<string>;
    notes?: Nullable<string>;
    terms?: Nullable<string>;
    version: number;
    pdf_url: unknown;
    template_id?: Nullable<number>;
    active_version_id?: Nullable<number>;
    parent_quote_id?: Nullable<number>;
    deposit_percent?: Nullable<number>;
    decline_reason?: Nullable<string>;
    created_by?: Nullable<number>;
    signature_url: unknown;
    signer_name?: Nullable<string>;
    signer_ip?: Nullable<string>;
    win_probability?: Nullable<number>;
    created_at: string;
    updated_at: string;
}

export interface Quote extends QuoteBase {
    workspace?: Workspace;
    client?: Client;
    assignee?: User;
    creator?: User;
    template?: QuoteTemplate;
    parentQuote?: Quote;
    sections?: QuoteSection[];
    lineItems?: QuoteLineItem[];
    activities?: QuoteActivity[];
    invoices?: Invoice[];
    shortCode?: QuoteShortCode;
    quoteFollowUps?: QuoteFollowUp[];
    trackingEvents?: QuoteTrackingEvent[];
    messages?: QuoteMessage[];
    winProbability?: QuoteWinProbability;
    quoteApprovals?: QuoteApproval[];
    versions?: Quote[];
    activeVersion?: Quote;
    parent?: Quote;
    comments?: Comment[];
    tasks?: Task[];
}

export type CreateQuotePayload = Omit<QuoteBase, 'id' | 'created_at' | 'updated_at' | 'deleted_at'>;
export type UpdateQuotePayload = Partial<CreateQuotePayload>;
