// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { QuoteWinProbability } from './quote-win-probability';

export type SignalDirection = 'positive' | 'negative';

export interface QuoteWinProbabilitySignal {
    id: number;
    probability?: Nullable<number>;
    weight?: Nullable<number>;
    sample_size: number;
    direction: SignalDirection;
    meta?: Nullable<Record<string, unknown>>;
    win_probability_id: number;
    key: string;
    label: string;
    created_at: string;
    updated_at: string;
    winProbability?: QuoteWinProbability;
}

export type CreateQuoteWinProbabilitySignalPayload = Omit<QuoteWinProbabilitySignal, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'winProbability'>;
export type UpdateQuoteWinProbabilitySignalPayload = Partial<CreateQuoteWinProbabilitySignalPayload>;
