// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { CatalogItem } from './catalog-item';
import type { CatalogItemVariant } from './catalog-item-variant';
import type { Nullable } from './model-helpers';
import type { PriceTier } from './price-tier';
import type { Quote } from './quote';
import type { QuoteLineItemTax } from './quote-line-item-tax';
import type { QuoteSection } from './quote-section';

export type DiscountType = 'percent' | 'fixed';

export interface QuoteLineItemBase {
    id: number;
    quantity: number;
    unit_price: number;
    cost_price?: Nullable<number>;
    discount_type?: Nullable<DiscountType>;
    discount_value?: Nullable<number>;
    subtotal: number;
    total: number;
    is_optional: boolean;
    quote_id: number;
    quote_section_id: number;
    catalog_item_id?: Nullable<number>;
    catalog_item_variant_id?: Nullable<number>;
    name: string;
    description?: Nullable<string>;
    unit?: Nullable<string>;
    price_tier_applied: boolean;
    base_unit_price: number;
    base_subtotal: number;
    tax_amount: number;
    base_tax_amount: number;
    base_total: number;
    notes?: Nullable<string>;
    sort_order: number;
    created_at: string;
    updated_at: string;
}

export interface QuoteLineItem extends QuoteLineItemBase {
    quote?: Quote;
    section?: QuoteSection;
    catalogItem?: CatalogItem;
    catalogItemVariant?: CatalogItemVariant;
    taxes?: QuoteLineItemTax[];
    priceTiers?: PriceTier[];
}

export type CreateQuoteLineItemPayload = Omit<
    QuoteLineItemBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdateQuoteLineItemPayload = Partial<CreateQuoteLineItemPayload>;
