// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Quote } from './quote';
import type { QuoteLineItem } from './quote-line-item';

export interface QuoteSectionBase {
    id: number;
    quote_id: number;
    title: string;
    sort_order: number;
    created_at: string;
    updated_at: string;
}

export interface QuoteSection extends QuoteSectionBase {
    quote?: Quote;
    lineItems?: QuoteLineItem[];
}

export type CreateQuoteSectionPayload = Omit<QuoteSectionBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateQuoteSectionPayload = Partial<CreateQuoteSectionPayload>;
