// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Workspace } from './workspace';
import type { User } from './user';
import type { QuoteTemplateSection } from './quote-template-section';
import type { QuoteTemplateLineItem } from './quote-template-line-item';

export interface QuoteTemplateBase {
    id: number;
    is_active: boolean;
    is_system: boolean;
    layout?: Nullable<Record<string, unknown>>;
    workspace_id: number;
    name: string;
    description?: Nullable<string>;
    industry?: Nullable<string>;
    cover_message?: Nullable<string>;
    notes?: Nullable<string>;
    terms?: Nullable<string>;
    usage_count: number;
    created_by?: Nullable<number>;
    created_at: string;
    updated_at: string;
}

export interface QuoteTemplate extends QuoteTemplateBase {
    workspace?: Workspace;
    creator?: User;
    sections?: QuoteTemplateSection[];
    lineItems?: QuoteTemplateLineItem[];
}

export type CreateQuoteTemplatePayload = Omit<QuoteTemplateBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateQuoteTemplatePayload = Partial<CreateQuoteTemplatePayload>;
