// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Quote } from './quote';
import type { QuoteLineItem } from './quote-line-item';

export interface QuoteSection {
    id: number;
    quote_id: number;
    title: string;
    sort_order: number;
    created_at: string;
    updated_at: string;
    quote?: Quote;
    lineItems?: QuoteLineItem[];
}

export type CreateQuoteSectionPayload = Omit<QuoteSection, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'quote' | 'lineItems'>;
export type UpdateQuoteSectionPayload = Partial<CreateQuoteSectionPayload>;
