// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Client } from './client';
import type { Invoice } from './invoice';
import type { Nullable } from './model-helpers';
import type { User } from './user';
import type { Workspace } from './workspace';

export interface RecurringInvoiceBase {
    id: number;
    subtotal: number;
    tax_amount: number;
    discount_amount: number;
    total: number;
    layout_snapshot: Record<string, unknown>;
    sections: Record<string, unknown>;
    start_date: string;
    end_date?: Nullable<string>;
    next_invoice_date: string;
    is_active: boolean;
    workspace_id: number;
    client_id: number;
    created_by: number;
    name: string;
    currency: string;
    frequency: string;
    interval: number;
    created_at: string;
    updated_at: string;
}

export interface RecurringInvoice extends RecurringInvoiceBase {
    workspace?: Workspace;
    client?: Client;
    createdBy?: User;
    invoices?: Invoice[];
}

export type CreateRecurringInvoicePayload = Omit<RecurringInvoiceBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateRecurringInvoicePayload = Partial<CreateRecurringInvoicePayload>;
