// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';

export interface RoleBase {
    id: number;
    name: string;
    display_name?: Nullable<string>;
    description?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export interface Role extends RoleBase {
}

export type CreateRolePayload = Omit<RoleBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateRolePayload = Partial<CreateRolePayload>;
