// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';

export interface Role {
    id: number;
    name: string;
    display_name?: Nullable<string>;
    description?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export type CreateRolePayload = Omit<Role, 'id' | 'created_at' | 'updated_at' | 'deleted_at'>;
export type UpdateRolePayload = Partial<CreateRolePayload>;
