// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { SubscriptionItem } from './subscription-item';
import type { Transaction } from './transaction';

export interface Subscription {
    id: number;
    trial_ends_at?: Nullable<string>;
    paused_at?: Nullable<string>;
    ends_at?: Nullable<string>;
    created_at: string;
    updated_at: string;
    billable?: unknown;
    items?: SubscriptionItem[];
    transactions?: Transaction[];
}

export type CreateSubscriptionPayload = Omit<Subscription, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'billable' | 'items' | 'transactions'>;
export type UpdateSubscriptionPayload = Partial<CreateSubscriptionPayload>;
