// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Subscription } from './subscription';

export interface SubscriptionItemBase {
    id: number;
    quantity: number;
    created_at: string;
    updated_at: string;
}

export interface SubscriptionItem extends SubscriptionItemBase {
    subscription?: Subscription;
}

export type CreateSubscriptionItemPayload = Omit<SubscriptionItemBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateSubscriptionItemPayload = Partial<CreateSubscriptionItemPayload>;
