// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Subscription } from './subscription';

export interface SubscriptionItem {
    id: number;
    quantity: number;
    created_at: string;
    updated_at: string;
    subscription?: Subscription;
}

export type CreateSubscriptionItemPayload = Omit<SubscriptionItem, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'subscription'>;
export type UpdateSubscriptionItemPayload = Partial<CreateSubscriptionItemPayload>;
