// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Workspace } from './workspace';
import type { Task } from './task';

export interface TaskStatusBase {
    id: number;
    is_default: boolean;
    is_system: boolean;
    workspace_id: number;
    name: string;
    slug: string;
    color: string;
    sort_order: number;
    created_at: string;
    updated_at: string;
}

export interface TaskStatus extends TaskStatusBase {
    workspace?: Workspace;
    tasks?: Task[];
}

export type CreateTaskStatusPayload = Omit<TaskStatusBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateTaskStatusPayload = Partial<CreateTaskStatusPayload>;
