// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { User } from './user';
import type { TaskStatus } from './task-status';
import type { Workspace } from './workspace';

export interface Task {
    id: number;
    due_date?: Nullable<string>;
    completed_at?: Nullable<string>;
    workspace_id: number;
    taskable_id: unknown;
    taskable_type: unknown;
    assigned_to: number;
    assigned_by?: Nullable<number>;
    task_status_id?: Nullable<number>;
    title: string;
    description?: Nullable<string>;
    created_at: string;
    updated_at: string;
    taskable?: unknown;
    assignedTo?: User;
    assignedBy?: User;
    status?: TaskStatus;
    workspace?: Workspace;
}

export type CreateTaskPayload = Omit<Task, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'taskable' | 'assignedTo' | 'assignedBy' | 'status' | 'workspace'>;
export type UpdateTaskPayload = Partial<CreateTaskPayload>;
