// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { TaskStatus } from './task-status';
import type { User } from './user';
import type { Workspace } from './workspace';

export interface TaskBase {
    id: number;
    due_date?: Nullable<string>;
    completed_at?: Nullable<string>;
    workspace_id: number;
    taskable_id: unknown;
    taskable_type: unknown;
    assigned_to: number;
    assigned_by?: Nullable<number>;
    task_status_id?: Nullable<number>;
    title: string;
    description?: Nullable<string>;
    created_at: string;
    updated_at: string;
}

export interface Task extends TaskBase {
    taskable?: unknown;
    assignedTo?: User;
    assignedBy?: User;
    status?: TaskStatus;
    workspace?: Workspace;
}

export type CreateTaskPayload = Omit<TaskBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateTaskPayload = Partial<CreateTaskPayload>;
