// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { CatalogItem } from './catalog-item';
import type { Nullable } from './model-helpers';
import type { User } from './user';
import type { Workspace } from './workspace';

export interface TaxBase {
    id: number;
    rate: number;
    inclusive: boolean;
    is_default: boolean;
    is_active: boolean;
    deleted_at?: Nullable<string>;
    workspace_id: number;
    name: string;
    created_by?: Nullable<number>;
    created_at: string;
    updated_at: string;
}

export interface Tax extends TaxBase {
    workspace?: Workspace;
    creator?: User;
    catalogItems?: CatalogItem[];
}

export type CreateTaxPayload = Omit<
    TaxBase,
    'id' | 'created_at' | 'updated_at' | 'deleted_at'
>;
export type UpdateTaxPayload = Partial<CreateTaxPayload>;
