// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Subscription } from './subscription';

export interface Transaction {
    id: number;
    billed_at: string;
    created_at: string;
    updated_at: string;
    billable?: unknown;
    subscription?: Subscription;
}

export type CreateTransactionPayload = Omit<Transaction, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'billable' | 'subscription'>;
export type UpdateTransactionPayload = Partial<CreateTransactionPayload>;
