// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Subscription } from './subscription';

export interface TransactionBase {
    id: number;
    billed_at: string;
    created_at: string;
    updated_at: string;
}

export interface Transaction extends TransactionBase {
    billable?: unknown;
    subscription?: Subscription;
}

export type CreateTransactionPayload = Omit<
    TransactionBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdateTransactionPayload = Partial<CreateTransactionPayload>;
