// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Workspace } from './workspace';
import type { Role } from './role';
import type { Permission } from './permission';
import type { DatabaseNotification } from './database-notification';

export interface User {
    id: number;
    email_verified_at?: Nullable<string>;
    two_factor_confirmed_at?: Nullable<string>;
    name: string;
    email: string;
    current_workspace_id: number;
    created_at: string;
    updated_at: string;
    workspaces?: Workspace[];
    ownedWorkspaces?: Workspace[];
    currentWorkspace?: Workspace;
    roles?: Role[];
    rolesTeams?: Workspace[];
    permissionsTeams?: Workspace[];
    permissions?: Permission[];
    notifications?: DatabaseNotification[];
    readNotifications?: DatabaseNotification[];
    unreadNotifications?: DatabaseNotification[];
}

export type CreateUserPayload = Omit<User, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'workspaces' | 'ownedWorkspaces' | 'currentWorkspace' | 'roles' | 'rolesTeams' | 'permissionsTeams' | 'permissions' | 'notifications' | 'readNotifications' | 'unreadNotifications'>;
export type UpdateUserPayload = Partial<CreateUserPayload>;
