// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { User } from './user';
import type { Plan } from './plan';
import type { Industry } from './industry';
import type { Invitation } from './invitation';
import type { WorkspaceSetting } from './workspace-setting';
import type { Invoice } from './invoice';
import type { WorkspaceUsage } from './workspace-usage';
import type { CreditNote } from './credit-note';
import type { FollowUpSequence } from './follow-up-sequence';
import type { CatalogItem } from './catalog-item';
import type { Client } from './client';
import type { QuoteTemplate } from './quote-template';
import type { Customer } from './customer';
import type { Subscription } from './subscription';
import type { Transaction } from './transaction';

export interface WorkspaceBase {
    id: number;
    settings_onboarded_at?: Nullable<string>;
    white_label_mode: boolean;
    agency_mode_enabled: boolean;
    agency_commission_rate: number;
    name: string;
    owner_id: number;
    currency: string;
    industry_id?: Nullable<number>;
    agency_commission_type: unknown;
    logo_url: unknown;
    primary_color: string;
    accent_color: string;
    address?: Nullable<string>;
    phone?: Nullable<string>;
    email?: Nullable<string>;
    website?: Nullable<string>;
    country?: Nullable<string>;
    tax_number?: Nullable<string>;
    favicon_url: unknown;
    custom_domain?: Nullable<string>;
    plan_id?: Nullable<number>;
    created_at: string;
    updated_at: string;
}

export interface Workspace extends WorkspaceBase {
    owner?: User;
    plan?: Plan;
    industry?: Industry;
    members?: User[];
    invitations?: Invitation[];
    settings?: WorkspaceSetting[];
    invoices?: Invoice[];
    usage?: WorkspaceUsage[];
    creditNotes?: CreditNote[];
    followUpSequences?: FollowUpSequence[];
    catalogItems?: CatalogItem[];
    clients?: Client[];
    templates?: QuoteTemplate[];
    customer?: Customer;
    subscriptions?: Subscription[];
    transactions?: Transaction[];
}

export type CreateWorkspacePayload = Omit<WorkspaceBase, 'id' | 'created_at' | 'updated_at'>;
export type UpdateWorkspacePayload = Partial<CreateWorkspacePayload>;
