// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Workspace } from './workspace';

export interface WorkspaceSettingBase {
    id: number;
    encrypted: boolean;
    workspace_id: number;
    group: string;
    key: string;
    value?: Nullable<string>;
    cast: string;
    created_at: string;
    updated_at: string;
}

export interface WorkspaceSetting extends WorkspaceSettingBase {
    workspace?: Workspace;
}

export type CreateWorkspaceSettingPayload = Omit<
    WorkspaceSettingBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdateWorkspaceSettingPayload =
    Partial<CreateWorkspaceSettingPayload>;
