// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Nullable } from './model-helpers';
import type { Workspace } from './workspace';

export interface WorkspaceSetting {
    id: number;
    encrypted: boolean;
    workspace_id: number;
    group: string;
    key: string;
    value?: Nullable<string>;
    cast: string;
    created_at: string;
    updated_at: string;
    workspace?: Workspace;
}

export type CreateWorkspaceSettingPayload = Omit<WorkspaceSetting, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'workspace'>;
export type UpdateWorkspaceSettingPayload = Partial<CreateWorkspaceSettingPayload>;
