// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Workspace } from './workspace';

export interface WorkspaceUsageBase {
    id: number;
    period: string;
    quotes_sent: number;
    invoices_sent: number;
    ai_credits_used: number;
    workspace_id: number;
    created_at: string;
    updated_at: string;
}

export interface WorkspaceUsage extends WorkspaceUsageBase {
    workspace?: Workspace;
}

export type CreateWorkspaceUsagePayload = Omit<
    WorkspaceUsageBase,
    'id' | 'created_at' | 'updated_at'
>;
export type UpdateWorkspaceUsagePayload = Partial<CreateWorkspaceUsagePayload>;
