// This file is auto-generated by eloquent-typegen. Do not edit manually.

import type { Workspace } from './workspace';

export interface WorkspaceUsage {
    id: number;
    period: string;
    quotes_sent: number;
    invoices_sent: number;
    ai_credits_used: number;
    workspace_id: number;
    created_at: string;
    updated_at: string;
    workspace?: Workspace;
}

export type CreateWorkspaceUsagePayload = Omit<WorkspaceUsage, 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'workspace'>;
export type UpdateWorkspaceUsagePayload = Partial<CreateWorkspaceUsagePayload>;
